### ISSUE TITLE
Subir bot básico

### ISSUE THREAD

**Issue by xValentim** [xValentim/hubot#1]

**Comment by xValentim** [comment]
Pra subir o bot básico, basta migrar tudo que está nesse repo https://github.com/xValentim/observability-yt para o repo hubot.

Se você copiar literalmente o que tem la, ele fará o deploy automático, então cuidado.

**Comment by xValentim** [comment]
@HudsonArauj @SamuelJabes Colocar essa task para o Tales quando ele aceitar o Invite.

**Comment by HudsonArauj** [comment]
querido dev @talesitf faça o seguinte :
Pra subir o bot básico, basta migrar tudo que está nesse repo https://github.com/xValentim/observability-yt para o repo hubot.

Se você copiar literalmente o que tem la, ele fará o deploy automático, então cuidado.
